name: conda-publish-env
python:
  - 3.10
  - 3.11
channels:
  - conda-forge
  - defaults
  - open3d-admin
dependencies:
    - python>=3.10, <3.12
    - pytorch>=2.0.0
    - numpy>=2.0.0
    - pandas>=2.2.0
    - tifffile
    - imagecodecs
    - scikit-learn>1.0.1
    - scikit-image>0.19.2
    - scipy>=1.10.0
    - requests>2.28.0
    - ipython>8.0.0
    - click>8.0.4