package:
    name: "tardis-em"
    version: "0.3.11"

source:
    path: ../

build:
    number: 0
    noarch: python
#    platform: osx-arm64
    script: {{ PYTHON }} -m pip install . -vv

requirements:
    host:
        - pip
        - python>=3.10,<3.12
    build:
        - python>=3.10,<3.12
        - pip
        - setuptools
    run:
        - python>=3.10, <3.12
        - pytorch>=2.0.0
        - numpy>=2.0.0
        - pandas>=2.2.0
        - tifffile
        - imagecodecs
        - scikit-learn>1.0.1
        - scikit-image>0.19.2
        - scipy>=1.10.0
        - requests>2.28.0
        - ipython>8.0.0
        - click>8.0.4
    optional:
        - plyfile
        - pyvista
        - open3d
        - nd2
        - roi

extra:
  recipe-maintainers:
    - RRobert92
    - tbepler

about:
    doc_url: https://smlc-nysbc.github.io/TARDIS/
    dev_url: https://github.com/SMLC-NYSBC/TARDIS
    home: https://github.com/SMLC-NYSBC/TARDIS
    license: MIT
    license_file: LICENSE
